variable review

In [1]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print #list상의 특징

<class 'tuple'>
1
2


<function print>

In [2]:
a =	{"a": "apple", "b": "orange", "c": 2014}# list로 하는 것이 아닌 표제어로 한다
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [3]:
a=[(1,2,3), (3,8,0)] #tuple -> ( , , ) 지금의 a 는 2 x 3행렬 표시임
print(type(a))
a#현재는 tuple두개가 들어있는 list

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [4]:
a=[(1,2,3); (3,8,0)] # 행렬 형태로 만들수 있는 방법이 없음
print(type(a))
a

SyntaxError: invalid syntax (<ipython-input-4-63b9716d4a0f>, line 1)

In [6]:
import numpy as np #import 하드 디스크에 있는 것을 내 memory에 올려놔주는 함수식이다 -> numpy라는 것은 함수로 되지 않음
#numpy라는 것을 diretory로 띄워라!  package를 불러오는 것. 
b = np.array(a)
print(b)#numpy가 제공하는 행렬형식의 값을 보여줌
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


위와 아래는 동일한 말

In [7]:
import numpy
b = numpy.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [8]:
print(b*b) #array 는 행렬아 아님 단순히 행렬처럼 생긴 것 -> 행렬의 곱이 안되는 것에서도 곱이 됨 b^2 = b*b

[[ 1  4  9]
 [ 9 64  0]]


In [11]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [13]:
c*c # matrix함수는 행렬로 바꿔주는 것이기 떄문에 에러가 남

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [12]:
c*c.T #행령의 열과 행을 바꿔주는 것(matrix flip)이기 때문에 에러없이 연산 가능 
#.T 는 transpose. 이것도 numpy 안에 있는 것이다.- matrix에 연관된 함수.

matrix([[14, 19],
        [19, 73]])

In [14]:
s = 'abcdef'#이러한 str은 str에 맞는 함수가 있다( +, - , * , / 와는 맞지 않겠지) 즉 객체지향적 함수 package가 있음

In [16]:
print(type(s))

<class 'str'>


In [17]:
s = 'abcdef'
print(s[0], s[5], s[-1], s[-6])#0부터 처음으로 본다 즉 s[0]=a, s[1]=b
print(s[1:3], s[1:], s[:3], s[:])#s[1:3]-> s안에 있는 것중 1부터 2까지 

a f f a
bc bcdef abc abcdef


In [ ]:
n = [100, 200, 300]
print(n[0], n[2], n[-1], n[-3])
print(n[1:2], n[1:], n[:2], n[:])

In [18]:
len(s)

6

In [19]:
s[1]+s[3]+s[4:]*10 #concatenate -> 붙이는 것 str도 기본 연산자가 가능하다

'bdefefefefefefefefefef'

In [20]:
s.upper()#.upper -> capotalize variable 은 class를 정의하는 것.그에따라 이용 함수도 달라진다 

'ABCDEF'

In [21]:
s = ' this is a house built this year.\n' 	# str에 스페이스도 들어갈 수 있음
s

' this is a house built this year.\n'

In [22]:
len(s)

34

In [23]:
result = s.find('house') 	    # index of first instance of string t inside s (-1 if not found)
result

11

In [24]:
result = s.find('this')	    # index of last instance of string t inside s (-1 if not found)
result

1

In [25]:
result = s.rindex('this')        # like s.find(t) except it raises ValueError if not found 
result #처음으로 나오는 것이 아니라 맨 마지막에 나오는 것 

23

In [26]:
s = s.strip()      	            # a copy of s without leading or trailing whitespace
s # strip 안에 있는 것 제거 s 를 바꾸려면 다시 재설정 해줘야 한다 s.strip 자체만 하면 그값이 나올뿐 s는 변동 x 

'this is a house built this year.'

In [27]:
tokens = s.split(' ')	        # split s into a list wherever a t is found (whitespace by default)
tokens #단어별로 자르고 싶으면 tokenize를 해주는 .split 함수를 써준다 -> 기준은 space 되어있을 떄 구간. 

['this', 'is', 'a', 'house', 'built', 'this', 'year.']

In [28]:
s = ' '.join(tokens)	        # combine the words of the text into a string using s as the glue
s # 다시 split 된 것을 붙임 

'this is a house built this year.'

In [29]:
s = s.split(' ')
s

['this', 'is', 'a', 'house', 'built', 'this', 'year.']

In [30]:
s =  ' '.join(tokens)
s

'this is a house built this year.'

In [31]:
s = s.replace('this', 'that')   # replace instances of t with u inside s
s # .replace 단어 바꾸기 

'that is a house built that year.'

# 크롤링

<여는태그>내용</닫는태그>
<여는태그 속성명="속성값">내용</닫는태그>
<여는태그 속성명="속성값" />  -> 내용이 없고 속성만 있는 경우
view-source: -> crawling
html: 전체 html 문서를 감싸는 태그입니다. 하나만 존재해야 하고 html 바깥에 DOCTYPE을 제외한 다른 태그가 있으면 안 됩니다.
head: html 문서에 대한 정보를 나타내는 부분입니다. 하나만 존재해야하고, html 바로 아래에 있어야합니다.
body: html 문서에서 실제적으로 보여지는 부분을 나타냅니다. 하나만 존재해야 하고, html 바로 아래, head 다음에 위치해야 합니다.
title: head 안에 들어가는 태그로 제목표시줄의 내용을 나타냅니다.
meta: 문서에 대한 설명을 표시합니다. 사람에게는 보이지 않고, 브라우저만 읽을 수 있습니다. 속성으로 charset="utf-8"이라고 한 것은 브라우저에게 한글인코딩을 UTF-8로 설정하라고 알린 겁니다. 이 부분이 있어야 한글이 깨지지 않습니다.
h1: body 안에서 제목을 표시하는 태그입니다. 중요도에 따라 h1부터 h2, h3, ..., h6까지 있습니다.
div: 구역을 표시하는 태그입니다. 눈에 보이지는 않지만 p와 img 태그를 하나의 구역으로 묶었습니다.
p: 문단을 표시하는 태그입니다. 여기 안에 글의 내용을 넣으면 됩니다.
img: 이미지를 표시하는 태그입니다. 아까 src라는 속성이 있었는데 src는 이미지 파일의 경로(위치)를 지정하는 속성입니다.

In [1]:
# _*_ coding: UTF-8 _*_
from urllib.request import urlopen # 큰 폴더 속에 들어 있는 작은 폴더를 가지고 오고 싶다면 from 함수를 써준다
from bs4 import BeautifulSoup
import csv

In [2]:
html = urlopen("http://www.naver.com")
html

## 웹문서 전체를 가져오기

In [3]:
bsObject = BeautifulSoup(html, "html.parser")
bsObject.html#위에 처럼 그냥 통으로 보는게 아니라 세부적으로 보고 싶다면 따로 그 목적인 BeuatifulSoupdmf 써주어야 한다

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="origin" name="Referrer"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=1100" name="viewport"/>
<meta content="NAVER" name="apple-mobile-web-app-title">
<meta content="index,nofollow" name="robots">
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="description">
<meta content="네이버" property="og:title"/>
<meta content="https://www.naver.com/" property="og:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" property="og:image"/>
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" property="og:description">
<meta content="summary" name="twitter:card"/>
<meta content="" name="twitter:title"/>
<meta content="https://www.naver.com/" name="twitter:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mob

In [4]:
bsObject.html

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="origin" name="Referrer"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=1100" name="viewport"/>
<meta content="NAVER" name="apple-mobile-web-app-title">
<meta content="index,nofollow" name="robots">
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="description">
<meta content="네이버" property="og:title"/>
<meta content="https://www.naver.com/" property="og:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" property="og:image"/>
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" property="og:description">
<meta content="summary" name="twitter:card"/>
<meta content="" name="twitter:title"/>
<meta content="https://www.naver.com/" name="twitter:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mob

## HEAD가져오기

In [35]:
bsObject.head#닫는 태그(/)가 항상 있어야 한다 없는 경우 맨믿에서 따로 닫아야한다

<head>
<meta charset="utf-8"/>
<meta content="origin" name="Referrer"/>
<meta content="text/javascript" http-equiv="Content-Script-Type"/>
<meta content="text/css" http-equiv="Content-Style-Type"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=1100" name="viewport"/>
<meta content="NAVER" name="apple-mobile-web-app-title">
<meta content="index,nofollow" name="robots">
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="description">
<meta content="네이버" property="og:title"/>
<meta content="https://www.naver.com/" property="og:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" property="og:image"/>
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" property="og:description">
<meta content="summary" name="twitter:card"/>
<meta content="" name="twitter:title"/>
<meta content="https://www.naver.com/" name="twitter:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.

## TITLE 가져오기 

In [36]:
bsObject.head.title #맨 마지막에 존재 연속적이어도 되지만 수직적이어도 상관없음

<title>NAVER</title>

In [5]:
bsObject.head.title.get_text()  # bsObject.head.title.text.strip()

'NAVER'

## meta 데이터 가져오기

In [6]:
0bsObject.head.find_all('meta')#()안에 있는 것을 다 찾으라는 뜻임 상위컨텐츠와 상위컨텐츠 안의 하위컨텐츠 까지 다 가져옴 -> 중복이 됨

[<meta charset="utf-8"/>,
 <meta content="origin" name="Referrer"/>,
 <meta content="text/javascript" http-equiv="Content-Script-Type"/>,
 <meta content="text/css" http-equiv="Content-Style-Type"/>,
 <meta content="IE=edge" http-equiv="X-UA-Compatible"/>,
 <meta content="width=1100" name="viewport"/>,
 <meta content="NAVER" name="apple-mobile-web-app-title">
 <meta content="index,nofollow" name="robots">
 <meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="description">
 <meta content="네이버" property="og:title"/>
 <meta content="https://www.naver.com/" property="og:url"/>
 <meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" property="og:image"/>
 <meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" property="og:description">
 <meta content="summary" name="twitter:card"/>
 <meta content="" name="twitter:title"/>
 <meta content="https://www.naver.com/" name="twitter:url"/>
 <meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobi

## meta 데이터의 모든 content 가져오기

In [7]:
for meta in bsObject.head.find_all('meta'):
    print(meta.get('content')) #property값을 가져오라고 할 때 getg함수를 쓴다 - 속성값을 가지고 오라는 것

None
origin
text/javascript
text/css
IE=edge
width=1100
NAVER
index,nofollow
네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요
네이버
https://www.naver.com/
https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png
네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요
summary

https://www.naver.com/
https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png
네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요


## meta 데이터 중 원하는 tag 가져오기

In [8]:
bsObject.head.find("meta", {"name":"description"}) #find all 이 아니라 find () 해서 그 부분만 가져올 수 있다. 

<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="description">
<meta content="네이버" property="og:title"/>
<meta content="https://www.naver.com/" property="og:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" property="og:image"/>
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" property="og:description">
<meta content="summary" name="twitter:card"/>
<meta content="" name="twitter:title"/>
<meta content="https://www.naver.com/" name="twitter:url"/>
<meta content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png" name="twitter:image"/>
<meta content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요" name="twitter:description">
<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="https://pm.pstatic.net/css/main_v190219.css" rel="stylesheet" type="text/css"/>
<link href="https://pm.pstatic.net/css/webfont_v170623.css" rel="stylesheet" type="text/css"/>
<link href="https://ssl.pstatic.net/sstat

In [9]:
for link in bsObject.find_all('a'):
    print(link.get_text(), link.get('href'))#bsObesct-> 전체|

연합뉴스 바로가기 #news_cast
주제별캐스트 바로가기 #themecast
타임스퀘어 바로가기 #time_square
쇼핑캐스트 바로가기 #shp_cst
로그인 바로가기 #account
네이버 /
네이버를 시작페이지로 http://help.naver.com/support/alias/contents2/naverhome/naverhome_1.naver
쥬니어네이버 http://jr.naver.com
해피빈 http://happybean.naver.com/main/SectionMain.nhn
자동완성 펼치기 javascript:;
한글 입력기 javascript:;
도움말 보기 https://help.naver.com/support/contents/contents.nhn?serviceNo=606&categoryNo=16658
ON선택됨 #
OFF #
로그인 https://nid.naver.com/nidlogin.login
자세히 https://help.naver.com/support/alias/search/word/word_16.naver
자세히 https://help.naver.com/support/contents/contents.nhn?serviceNo=606&categoryNo=16659
도움말 https://help.naver.com/support/service/main.nhn?serviceNo=606&categoryNo=1987
신고 https://help.naver.com/support/contents/contents.nhn?serviceNo=605&categoryNo=18215
검색어저장 켜기 javascript:;
자동완성 끄기 javascript:;
도움말 https://help.naver.com/support/service/main.nhn?serviceNo=606&categoryNo=1987
신고 https://help.naver.com/support/contents/contents.nhn?serviceNo=605&categoryNo=18215